name: Broadcast
version: 1.2
main: dk.noxitech.broadcast.main
commands:
  broadcast:
    description: Send en besked til alle spillere.
    usage: /broadcast <besked>
    permission: broadcast.use
    permission-message: §8[ §e§lBROADCAST §8] §cNo Access!
    aliases:
      - bc